# 应用名
app_name: "kafka-client"
server:
  http_addr: ":9980"

# 日志配置
log:
  level: "debug" # 日志级别: debug, info, warn, error
  format: "json" # 日志格式: json 或 console
  enable_caller: true # 是否记录调用者信息
  # output_paths: ["stdout", "./logs/all.log"] # stdout, stderr, 或文件路径
  # error_output_paths: ["stderr", "./logs/error.log"]

  # lumberjack 轮转配置
  lumberjack:
    filename: "./logs/gateway.log"
    max_size: 10 # 单个文件最大大小 (MB)
    max_backups: 5 # 最多保留备份数
    max_age: 30 # 旧文件最多保存天数
    compress: false # 是否压缩旧文件

# kafka配置
kafka:
  brokers: ["192.168.161.73:9092"]
  topics:
    - yddk.radar.target
    - yddk.radio.detection
    - yddk.adsb.cat021
    - yddk.radio.remoteRecognition
    - dkyj.target.locus
    - dkyj.target.fusion
    - dkyj.target.appear
    - dkyj.target.disappear
  group_id: "go-kafka-client"